### ISSUE TITLE
Report `devtest` numbers

### ISSUE THREAD

**Issue by satwikkottur** [billkunghappy/DSTC_TRACK4_ENTER#4]
Hello @billkunghappy,

Could you please report the `devtest` numbers for your model? It would help us crosscheck evaluation at our end. 

Thanks!

**Comment by billkunghappy** [comment]
About the `devtest` numbers you mentioned, do you meant the evaluation scores with single round evaluation?
If so, here is the score:
## Subtask1: 
### furniture:
* 'action_accuracy': 0.9510416666666667,
* 'action_perplexity': 1.213177261912038,
* 'attribute_accuracy': 0.5454545454545454
### fashion
* 'action_accuracy': 0.9714867617107943,
* 'action_perplexity': 1.2224478765094913, 
* 'attribute_accuracy': 0.3571409949077077,
## Subtask2:
### furniture:
* BLEU:0.1526
* 'r1': 0.24479166666666666, 
* 'r5': 0.5354166666666667,
* 'r10': 0.659375, 
* 'mean': 16.376041666666666,
* 'mrr': 0.38078858420660117
### fashion
* BLEU: 0.1698
* 'r1': 0.2158859470468432, 
* 'r5': 0.5631364562118126,
* 'r10': 0.7382892057026477, 
* 'mean': 11.791242362525459, 
* 'mrr': 0.37077830227898556
## Subtask3:
### furniture:
* joint_accuracy: 0.6566278302923719, 
* "act_rec": 0.8141349747197186,
* "act_prec": 0.8448728185240105,
* "act_f1": 0.8292191435768261,
* "slot_rec": 0.8032048596564726,
* "slot_prec": 0.782072200693453,
* "slot_f1": 0.7924976748992457
### fashion
* joint_accuracy: 0.5108083322415826, 
* "act_rec": 0.7105987161011398,
* "act_prec": 0.7539616346955796,
* "act_f1": 0.7316382275578338,
* "slot_rec": 0.7225085229525093,
* "slot_prec": 0.728515468862419,
* "slot_f1": 0.7254995621367725

**Comment by satwikkottur** [comment]
Hello @billkunghappy ,

Thanks a lot for these numbers. However, the first phase of evaluation on `devtest` is on the entire dialog (all the rounds) and not just the single round. Could you please add those numbers as well? We will compute these at our end as well, this serves as an additional layer of confirmation.

**Comment by billkunghappy** [comment]
OK, here are the evaluation scores on the entire dialogue:
## Subtask1
### furniture:
* 'action_accuracy': 0.8044867437117607,
* 'action_perplexity': 1.796027949113117,
* 'attribute_accuracy': 0.7096774193548387
### fashion:
* 'action_accuracy': 0.8512136372058551,
* 'action_perplexity': 1.8132851385107929,
* 'attribute_accuracy': 0.6956833602218424
## Subtask2
### furniture:
* BLEU Score: 0.1067
* 'r1': 0.2035350101971448,
* 'r5': 0.4397008837525493,
* 'r10': 0.5691366417403128,
* 'mean': 19.6649898028552,
* 'mrr': 0.3197837728069033
### fashion:
* BLEU Score: 0.1285
* 'r1': 0.21456364647026124,
* 'r5': 0.48823420418751157,
* 'r10': 0.6390587363350009,
* 'mean': 15.123957754307948,
* 'mrr': 0.34611778886003314

**Comment by satwikkottur** [comment]
Thank you @billkunghappy !
